title: Subhash Jha
author: Subhash Jha
theme: jekyll-theme-midnight

social-network-links:
  email: "subahshjha.mail@gmail.com"
  github: jhasubhash
  twitter: subhashjha333
  linkedin: scjha

url-pretty: "subhashjha.in"
github:
  is_project_page: false
